### ISSUE TITLE
Nothing works at all after the last update. 

### ISSUE THREAD

**Issue by abstacek** [veista/nilan#10]
Nothing works at all after the last update. ( 1.0.25)
![image](https://user-images.githubusercontent.com/95470159/206651686-5c6bd319-ebca-4a92-83a7-ef81e075bf0f.png)

**Comment by abstacek** [comment]
Updated to version 1.0.19

**Comment by veista** [comment]
That is weird. Try removing and adding the integration again. Also could you report your ModBus version to the other Issue, thanks!

**Comment by abstacek** [comment]
Where can I find the ModBus version?

**Comment by veista** [comment]
> Where can I find the ModBus version?

It is a sensor in diagnostic. Scroll down on the device page.

**Comment by abstacek** [comment]
Ok. Thanks. ModBus Version is 22.

**Comment by veista** [comment]
Thank you! Did you get the 1.0.25 working. It should work normally on COMBI 302

**Comment by abstacek** [comment]
Yes, I tried removing the integration and adding it again and it works.
I have two wishes that I would like to resolve if possible.

1. How to turn off the electric preheating of the air (polar version)?

2. Can the supply fan be stopped when defrosting the evaporator? I tried via node-red, but maybe I'm doing something wrong.

**Comment by veista** [comment]
Hi, If these can't be done in the HMI, these can't be done by the Integration. The Integration can't add functionality to your device.

If these are possible in the HMI open  a new issue.
