### ISSUE TITLE
Add support for VGU180 EK

### ISSUE THREAD

**Issue by jyrkij** [veista/nilan#105]
Hi,

Would it be possible to add support for VGU180 EK?  The error in debug log is:

```
2023-12-04 13:47:17.881 DEBUG (MainThread) [custom_components.nilan.config_flow] Device Type 38 not found in supported devices list
```

Here's the device type plate:

![23-11-13 13-55-37 3803 (kopio)](https://github.com/veista/nilan/assets/9883/d4f25f50-4b97-4a13-8502-5be006f51325)

And I suppose this is the device info page:

![23-12-04 13-48-35 3865 (kopio)](https://github.com/veista/nilan/assets/9883/5f670e8c-9c76-4b9a-a710-eda739eaf798)

**Comment by veista** [comment]
Sure thing. I will add this ASAP.

**Comment by veista** [comment]
Should be working in the latest release.

**Comment by jyrkij** [comment]
Thank you!  The integration works, the device is recognised and communicates correctly.  There are missing registries though (and possibly some extra registries as well).  [2021-01-Modbus_CTS602_w_HMI350T_Modbus.pdf](https://www.en.nilan.dk/Files/Files/Engelsk/Downloads/7.%20Modbus%20-%20BACnet/2021-01-Modbus_CTS602_w_HMI350T_Modbus.pdf) lists at least central heating registries as supported (registry group 1800).  I haven't gone through the whole document so there might be some other registries missing as well.

**Comment by veista** [comment]
As I don't have access to your device:
1. Add your device number to the regisry_map.py on the registries you think your device supports
2. Cross-check from your HMI panel that the registries actually work as intended
3. Create a pull request so that everybody can benefit from your work

Thanks!
