### ISSUE TITLE
Add support for Nilan CompactS

### ISSUE THREAD

**Issue by convicte** [veista/nilan#110]
Hi,

I was able to modify the `device_map.py file to include all the registers working for this device, and thus far it's working just fine.
There are some idiosyncrasies in the sensor names (e.g. T7 should be T2), but that is very minor.

Here is the output of the debug error:
`2023-12-30 23:47:17.881 DEBUG (MainThread) [custom_components.nilan.config_flow] Device Type 10 not found in supported devices list`

I am not able to see the nameplate to provide a picture of it, but please see the requested Device Type information and the picture of the unit itself.

https://www.en.nilan.dk/products/ventilation-with-heating/ventilation-and-hot-water-production/compact-s

I'll follow up this initial report with a version of the `device_map.py` which works in my instance.

**Comment by convicte** [comment]
![2023-12-30 17 49 11](https://github.com/veista/nilan/assets/78666770/19df6237-495d-4f45-8f00-e6b903a4c077)

![2023-12-30 17 49 55](https://github.com/veista/nilan/assets/78666770/f3b946eb-6a4c-4479-b3b2-8a8125889c2c)

![2023-12-30 21 44 09](https://github.com/veista/nilan/assets/78666770/d779e437-31bb-489d-9578-b8641a3be339)

**Comment by veista** [comment]
Great! I will check your work asap. As for T2 -T7. T7 and T2 are the same sensor. T2 just stops working if you have an after heating element. I do not know why this is. T7 works always and T2 not. That is why just read T7 instead of trying to figure if someone has an after heating element.

**Comment by veista** [comment]
And please do make a pull request with your changes.
