### ISSUE TITLE
Latest update created orphaned device

### ISSUE THREAD

**Issue by convicte** [veista/nilan#122]
![image](https://github.com/veista/nilan/assets/78666770/1d8bceda-d957-406b-9b5a-8400b818efd5)

No way to delete it from HA without having to delete the integration, which I am afraid will mess all the sensors up as well.

![image](https://github.com/veista/nilan/assets/78666770/caa510e9-7ab8-44cd-bc85-ecd9f14f5ea0)

**Comment by veista** [comment]
I'm not sure what your issue is. This is something you have made yourself?

Just keep using your fork if you don't want to use this one.

**Comment by convicte** [comment]
Thanks for the prompt reply.

I am not using a fork, but your repo all along since last year.

I've updated today to the latest version, which created a new device under the integration while the old device was left with 2 orphaned entities. Deleting these entities didn't help, and I am stuck with an empty device.

Not sure if deleting the integration all together to add it again may mess up the existing sensors any further.

Any ideas?

**Comment by veista** [comment]
It would be nice to know which version number you are using.

**Comment by convicte** [comment]
1.2.12 at the moment, updating from 1.2.10

**Comment by veista** [comment]
#110 this is an issue you opened... support for CompactS was introduced in 1.2.12. I cant fix your code. Just reinstall or keep using your own fork.

**Comment by convicte** [comment]
To reiterate, I was not using a fork, but can understand why you would think that.
It's also understandable that you get frustrated with the situation, since it's probably related to home assistant handling more than your integration.

I've ended up deleting the whole integration and re-downloading it. This deleted both devices without messing up the sensors.

I'll review the sensors in more detail as there are several climate entities which are not sensible. I'll try to create a pull request to correct this.

For example there is a separate climate entity for top and bottom water heater part even though there is no control over them separately. There is only one.

There are also some sensor duplicated, probably from another device.
