### ISSUE TITLE
No Response received from the remote unit/Unable to decode response

### ISSUE THREAD

**Issue by gllmlbrt** [veista/nilan#14]
Hi, 
Currently on 1.1.1B, and since release 1.0.25 I have after many hours of perfect function and error as follow:
```
Logger: homeassistant.components.modbus.modbus
Source: components/modbus/modbus.py:391
Integration: Modbus (documentation, issues)
First occurred: 05:58:02 (1 occurrences)
Last logged: 05:58:02

Pymodbus: Nilan: Modbus Error: [Input/Output] No Response received from the remote unit/Unable to decode response
```
And then all entities generate an error like this one:
```
Logger: custom_components.nilan.device
Source: custom_components/nilan/device.py:2204
Integration: Nilan (documentation, issues)
First occurred: 05:58:02 (988 occurrences)
Last logged: 08:42:34
Could not read get_time
```
Reloading the integration does not fix it.
Restarting Hass core does not fix it.
To make it work again I need to reboot the bridge and **then** reload the integration.
Then it work flowlessly for some 8-10 hours and crashes again...

I will try now to revert to pre-1.0.25 and see over long time if it occurs again...

My device is Comfort series we just added to the supported devices.
This did not occur before 1.0.25 ( in the beta versions we tested before).

**Comment by veista** [comment]
That is weird. I have it running fine. It must be related to the bridge somehow.

**Comment by veista** [comment]
P.s. there shouldn't be anything different in the newest version in your case.

**Comment by gllmlbrt** [comment]
Issue appears to have disappeared in 1.1.2.B. maybe a coincidence... You can close the issue

**Comment by veista** [comment]
Ok, it must be a coincidense.
