### ISSUE TITLE
Unsupported Device VP18C Compact M2 M/køl

### ISSUE THREAD

**Issue by DUC750** [veista/nilan#149]
Could it be possible to integrate my Nilan device? 
I hope I have included all the necessary data. 
Thank you in advance.

![type plate](https://github.com/user-attachments/assets/d7a51bda-79ad-4be2-b2ce-584f741dc7fd)

![show data - type](https://github.com/user-attachments/assets/1ddabc88-fcc6-4bc0-a130-6319d6794739)

Log: 2024-09-30 20:58:53.751 DEBUG (MainThread) [custom_components.nilan.config_flow] Device Type 11 not found in supported devices list

**Comment by veista** [comment]
Sure thing. I will add it this week.

**Comment by DUC750** [comment]
Übersetze ins englische: so cool! Ich freue mich tierisch darauf. Vielen vielen Dank 😃

**Comment by DUC750** [comment]
Übersetze ins englische: so cool! Ich freue mich tierisch darauf. Vielen vielen Dank 😃

**Comment by DUC750** [comment]
So cool! I’m really looking forward to it. Thank you so much 😃

**Comment by DUC750** [comment]
Hi @veista, I wanted to ask if you have already added the device? 
Regards, DUC

**Comment by veista** [comment]
Hi, I am terribly sorry, but I have simply no time right now. I will add this as soon as I can. Thank you for your patience and understanding.

**Comment by DUC750** [comment]
Oh no, that’s not what I meant. I have no intention of rushing someone who develops such great things for the community in their free time. I just wanted to ask if I missed something. It takes as long as it takes. :-)

**Comment by DUC750** [comment]
Hello @veista,

I was a bit impatient and went ahead with the implementation of my device myself. Everything seems to be working fine so far. If you like, you can use the attached file.
[device_map.zip](https://github.com/user-attachments/files/17573497/device_map.zip)

Cheers,
DUC

**Comment by veista** [comment]
That is great. If you could do a pull request, that would be perfect.

**Comment by DUC750** [comment]
Never done it before, but there’s always a first time for everything. I’ll give it a try :-)

**Comment by DUC750** [comment]
#151
