### ISSUE TITLE
T4 sensor

### ISSUE THREAD

**Issue by abstacek** [veista/nilan#15]
Hi, I have a feeling if there is an error with the "Waste Air Temperature" display on the Combi 302 model. As the sensor.py file has the same name for the T4 and T6 sensors.
It is precisely the data from the T4 sensor that I am missing. You can look at it? Thank you.

![fd](https://user-images.githubusercontent.com/95470159/207581437-a44ba653-1c3c-49db-a1b7-19ac12ae05ea.png)

**Comment by veista** [comment]
Indeed. I will have to change the naming convention on these sensors since they are not consitent between models.

**Comment by veista** [comment]
T6 is evaporator yes, but it is the last sensor before waste in your model too. Can you confirm that the waste temperature in you HMI is actually T4? On other models with a compressor it is T6.

**Comment by veista** [comment]
And I dont mean the sensor name. I mean the temperature in the front panel picture.

**Comment by abstacek** [comment]
The unit also has a passive heat exchanger. The latter triggers the defrost based on the T4 sensor. It also has a T6.
![F51ADECF-F33F-4F49-A5FD-5A0055506993](https://user-images.githubusercontent.com/95470159/207626824-0202ba3d-f2f7-4f74-8ff8-f451458bbd98.jpeg)
![33638BF4-6771-4301-B85C-90D342670DBF](https://user-images.githubusercontent.com/95470159/207626893-c4d7062d-6ee8-49b3-8473-ef6a50fb2b99.jpeg)
![47D820CC-4169-46C1-A86E-FA049F0A4F8A](https://user-images.githubusercontent.com/95470159/207626926-dead0534-a45d-4add-a537-3c65007eeab3.jpeg)

**Comment by abstacek** [comment]
Hi. T2: Supply air sensor is now missing. On the contrary, I see T7 and the combi 302 does not have it. Maybe just misnamed.

**Comment by veista** [comment]
T7 == T2 it is just the register name. I do not know how it internally works, but T7 always gives a value, T2 doesn't. This doesn't relate to the original issue and will not be fixed.
