### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by abstacek** [veista/nilan#2]
Is support for MQTT planned?

**Comment by veista** [comment]
How would that work? If you want to send the data from Nilan to a mqtt broker, I believe that there is a solution for that.

**Comment by abstacek** [comment]
Hi, thanks, I'll look into it.
Could you please add a function to advance the time between defrosts? This option in the HMI is Thank you.

**Comment by veista** [comment]
Hi, could you please open a new issue and close this one if the issue is resolved. I will look into adding those features when I have time.
