### ISSUE TITLE
Nilan <-> Waveshare RS485-ethernet <-> HA Nilan integration 'failed to connect' error.

### ISSUE THREAD

**Issue by Magifi** [veista/nilan#23]
Hi again and sorry for bothering with stupid questions (perhaps)

My setup:
Nilan EC CTS602
Waveshare RS485 TO ETH (B) converter https://www.waveshare.com/wiki/RS485_TO_ETH_(B)
Raspberry Pi 3 and Home Assistant running in container
Nilan integration installed from HACS

When trying to add integration, I get 'Failed to connect' error:
![image](https://user-images.githubusercontent.com/119972006/208537145-7d35befb-090d-42bf-9f93-4b7ec89f096e.png)

I've managed to set up my waveshare converter (or at least I thinks so):
![image](https://user-images.githubusercontent.com/119972006/208537346-5c5f1775-090c-4727-925d-c2c36587a315.png)
![image](https://user-images.githubusercontent.com/119972006/208537412-d607b6e8-b957-41c5-a2b7-21dd948cc49b.png)

Loggin gives following:
'2022-12-20 00:14:37.435 ERROR (MainThread) [pymodbus.client.sync] Connection to (192.168.1.200, 502) failed: timed out'

I'm quite sure that this has something to do with my waveshare configs? First I thought that this problem is caused by running HA in container and mapping not workin between container and host. But then found out that Host <-> HA running in container have all the ports opened as a 'default' I guess. 

When loggin in to my router settings, I can see waveshare IP in the ARP/RARP Table.

Perhaps some of you who has managed to get this integration work with waveshare could help. All the help is highly appreciated and hopefully even rewarded in the end.

**Comment by veista** [comment]
Hi, failed to connect means that no data was exchanged. Check if you can ping it through HA.

**Comment by Magifi** [comment]
Did that on host (raspberry os) and no answer. As well my laptop couldn’t get answer. So the problem must be with the converter network settings. Too tired to go on, have to continue tomorrow if time schedules allow. Thanks for the help 👍

**Comment by MKBU2** [comment]
Configuration is identical to mine and for me it works. Sharewave and Raspberry HA are connected to same switch.

**Comment by Magifi** [comment]
Well, some time it's good to take a break and continue later. During the day I was trying to figure out what could be the problem. Double checking the ip addresses and stupid mistake was found. Third chapter of ip should have been 0 but I typed 1. So changing those three ip adresses in VirCom configuration tool made it work and I could connect Nilan with no problems.

There's some strange behaviour still goin on. Temperatures and other items are jumping like crazy and some times shows 'unknown'. I also had to remove and reinstall integration before anything showed up. I'm not sure but perhaps my other raspberry running openHAB parallel to this could cause some weird stuff. It's still stable and shows everything like before. But this is one step forward and great approvement! Thanks for all the help.

![image](https://user-images.githubusercontent.com/119972006/208766939-c6f2d744-d8b0-4b70-b41c-79f9b2c2c6cc.png)
![image](https://user-images.githubusercontent.com/119972006/208766993-631fe691-20fa-410a-bcbf-fed2fb87446c.png)
![image](https://user-images.githubusercontent.com/119972006/208767037-b55faddd-c1e8-4bd2-921e-53c3d3c7322a.png)

**Comment by Magifi** [comment]
Well that was a short run. Don't know what I messed (perhaps configurations.yaml and logger rows were bad). So I deleted those rows and restarted HA (couple of times). Now nothing and this is what I found from Nilan logs in the frontend:

2022-12-20 23:33:20.249 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Nilan for nilan
File "/config/custom_components/nilan/__init__.py", line 39, in async_setup_entry
File "/config/custom_components/nilan/device.py", line 60, in setup
File "/config/custom_components/nilan/device.py", line 124, in get_machine_type

My own fault but you learn from your mistakes, right? I know this is not topic related but perhaps someone else can get few tips of these posts.. Like I have done thousand times when faced a problem and have started googling around.

**Comment by veista** [comment]
What is the question? I think you should remove the other device from the modbus, you can NOT have multiple hosts on modbus RTU since this creates a competition conflict. This error comes from not being able to read the register.

**Comment by veista** [comment]
If your Modbus bridge supports multiple TCP masters you could add your other solution like that, provided they have different IP addresses.

**Comment by Magifi** [comment]
> What is the question? I think you should remove the other device from the modbus, you can NOT have multiple hosts on modbus RTU since this creates a competition conflict. This error comes from not being able to read the register.

My bad (again). I thought that Nilan controller is the master and other devices are slaves (like local control panel + other devices connected via modbus). So my assumption was that there could be more than one device and all could run parallel at the same time causing no problem to each other. I will remove my other Raspberry with RS485 - usb converter as soon as I’m familiar enough with HA.

Mistakes happen and learning takes time..

**Comment by veista** [comment]
And By-the-way you should check the validity of your configuration.yaml from developer tools 
![image](https://user-images.githubusercontent.com/91916713/208775641-56bfcd34-70cc-4b6f-8801-5603779240bd.png)
