### ISSUE TITLE
Please add T4 start de-icing support for Combi 302 Polar

### ISSUE THREAD

**Issue by abstacek** [veista/nilan#24]
Please add the Combi 302 Polar function in the HMI De-icing T4 start de-icing option to set ON/OFF. Thank you.
![IMG_3472](https://user-images.githubusercontent.com/95470159/208618353-e4ab13d9-a7b8-4369-8082-68712a27d18b.jpg)

**Comment by veista** [comment]
I believe it is already there "Pre-Heating Temperature"

**Comment by abstacek** [comment]
You may have deleted it. I only have Pre-Heating Effect.

**Comment by veista** [comment]
Ok, I will check.

**Comment by veista** [comment]
Hi. Yes there is a typo, will fix in next release.

**Comment by veista** [comment]
Hi, Even though there was a typo, it should not affect this. You should have this entity. "Pre-Heating Temperature"

**Comment by abstacek** [comment]
I don't really have this entity. I have 76 entities but this one is missing.
![BB713944-F506-4F1C-84EF-08A75B156B06](https://user-images.githubusercontent.com/95470159/208760228-4b72a6ce-77e4-4c5f-8e68-942e85d22784.png)

**Comment by veista** [comment]
Yes, there we two mistakes, deleted the previous comment.
