### ISSUE TITLE
Time betw.de-icing

### ISSUE THREAD

**Issue by abstacek** [veista/nilan#3]
Please add Time between defrosts. This option is available in the HMI. Thank you.

**Comment by abstacek** [comment]
Hi, has the time between defrosts been added yet? Thank you.

**Comment by veista** [comment]
No. I will add it when I have time, there are some issues in my code since I havn't prepared for it. My device doesn't have those and there is a naming conflict.

**Comment by abstacek** [comment]
OK

**Comment by veista** [comment]
Hi, I added better support for defrost functions on your model. I also found out that the fan speeds are available, so added those as well.

**Comment by abstacek** [comment]
Hi, it works perfectly. Thank you. I have one more question. Do you think it is possible to somehow turn off the preheating of the air before the modbus? I noticed that the preheat takes over 1200W. It is a function of the polar units and it is possible to turn it off, but I have no idea how. It would be great if it was possible.
![IMG_0443](https://user-images.githubusercontent.com/95470159/204981025-5d31cac6-87f9-49c1-8169-b2c9194f921d.PNG)

**Comment by abstacek** [comment]
It would also be nice if the compressor could be turned off in a different way than by lowering the desired temperature. Ideally a switch in HA.

**Comment by abstacek** [comment]
Here is the option in the HMI.
![5B5A1A37-1B55-40B4-8235-F15EC134539C](https://user-images.githubusercontent.com/95470159/205093216-95289fd9-6eaa-47b7-8b3b-ed31d4c9f51b.jpeg)
![BD6C3D71-74C6-4531-BD89-E465A682E0A7](https://user-images.githubusercontent.com/95470159/205093265-c9b4345a-4010-4014-899e-577795491fbc.jpeg)
![9F515403-F37D-47BC-86EF-F3390EC7306C](https://user-images.githubusercontent.com/95470159/205093284-6e43a82f-3df1-4211-82ba-78f10c7e5348.jpeg)
