### ISSUE TITLE
Unsupported Device: VPL 15

### ISSUE THREAD

**Issue by janner** [veista/nilan#35]
Debug log:
> 2023-01-10 18:35:09.225 DEBUG (MainThread) [custom_components.nilan.config_flow] Device Type 4 not found in supported devices list

Attached is a picture of the plate.
![IMG_1151](https://user-images.githubusercontent.com/696691/211614622-958f90ba-c95d-44cf-b108-a7895df6ad07.jpg)

**Comment by veista** [comment]
Thanks. Could you also take a picture of the menu item requested.

**Comment by veista** [comment]
Added support.

**Comment by janner** [comment]
This is the non-HMI CTS602, so I'm guessing this is the information you are looking for.
![IMG_1153](https://user-images.githubusercontent.com/696691/211764031-a7ca104c-34fa-4bcd-be61-baf24f3c8faa.jpg)
![IMG_1152](https://user-images.githubusercontent.com/696691/211764038-434c0aa9-1bc3-4e07-af71-6b1159db5710.jpg)
![IMG_1155](https://user-images.githubusercontent.com/696691/211764882-cc9f3e11-9680-4613-ba08-48b358792ed0.jpg)

**Comment by veista** [comment]
Yes, thank you very much. Will fix the type on next release, so you will have to remove and add the integration again.
