### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by SalifTraoure** [veista/nilan#36]
Hi,

For a newbie,  any suggestions on how to customize your code to also capture Nilan Compact version with 602 control ? 
I guess it should be simple to add the relevant input and holding registers that are added for the water heating. 
The product
https://www.nilan.no/produkter/ventilasjon-med-oppvarming/ventilasjon-varmtvann-og-oppvarming/compact-p-air9
The Modbus mapping. 
https://www.nilan.no/Files/Files/Norsk/Download/7.%20Modbus%20-%20BACnet/2021-01-Modbus_CTS602_w_HMI350T_Modbus.pdf

The newbie tip would involve how to customize and install manually instead of using HACS.

**Comment by veista** [comment]
Nilan Compact is a CTS700 Device. Support for this will come in version 1.2.0. It is a time consuming addition, so it might take some months.
