### ISSUE TITLE
Unsupported device (Comfort 300 LR Light HMI/Waveshare RS485 to ETH (B)

### ISSUE THREAD

**Issue by JakobPP** [veista/nilan#52]
Hello

Thanks for your great work, I am very much looking forward to finally getting my HVAC online at some point.

I've been struggling with getting the plugin to connect with my Comfort 300 however. I've already been over all the wiring, termination etc. I have an powermeter online on the bus as well (PME3250) and I've measured correct voltage levels and "activity" on connection terminals at the plug on the HVAC unit itself. So, im fairly confident that this issue has to solved on "the software side".
Im using the waveshare, and pasting in my config at the end just for reference.

I hope the info supplied below is what you need, or else please let know. Thanks again.

HA debug log when trying to configure the plugin:

2023-03-07 21:07:09.339 DEBUG (MainThread) [custom_components.nilan.config_flow] Device Type 2 not found in supported devices list

Modelplate:

![Screenshot from 2023-03-07 21-09-03](https://user-images.githubusercontent.com/14965472/223541318-fadc02e4-7633-407b-b920-f34e5dbda960.png)

HMI:

![Screenshot from 2023-03-07 21-09-22](https://user-images.githubusercontent.com/14965472/223541378-5684219a-d4ee-494f-9a9b-67a522f03492.png)

Waveshare config (for reference):

![Screenshot from 2023-03-07 21-13-55](https://user-images.githubusercontent.com/14965472/223541749-e6075f71-df79-4cb9-8d52-8e0358d61bf9.png)

**Comment by veista** [comment]
Great! I will add this ASAP, by the end of the week.

**Comment by JakobPP** [comment]
Excellent, Thanks!Venlig hilsen - - Best regardsJakob Pilgaard PedersenDen 7. mar. 2023 kl. 23.37 skrev Taneli Veistinen ***@***.***>:﻿
Great! I will add this ASAP, by the end of the week.

**Comment by veista** [comment]
The device is now added.

**Comment by JakobPP** [comment]
Thanks once again veista for quick response. Its been running fine since then. I just wanted to check back in, in case anyone else is looking for help with a similar solution using the Waveshare.

Its possible to use the gatway in Modbus TCP server mode as well.

Posting screenshot for reference.

![Screenshot from 2023-03-21 20-29-38](https://user-images.githubusercontent.com/14965472/226720598-55ff6ed7-2127-47d4-85c5-ff91ef689390.png)
