### ISSUE TITLE
Integrating VP18cCom via RS485 serial USB

### ISSUE THREAD

**Issue by whoami-pi** [veista/nilan#55]
Hi,

I'm trying to connect my Nilan VP18cCom via RS485 serial USB with HA (using also CTS602).
I'm getting the error message "Unsupported Device" during the integration of Nilan.

I'm new at HA, the same interface was working before via PI and Node Red.
I've added this into configration.yaml and restarted HA:
`# Logger
logger:
  default: critical
  logs:
    custom_components.nilan: debug
    custom_components.hacs: debug`

But I'm still unable to see any log entries in Log-book. Have also activated debug protocoll for the HACS device.
Here is my selection:
![image](https://user-images.githubusercontent.com/59413296/224510763-31d1f807-8b4f-4aad-ad43-565bd0b4a9e1.png)

As the path seems to be correct:
![image](https://user-images.githubusercontent.com/59413296/224510746-f0c471e3-bf53-4f1f-9779-dc93f2f31bd0.png)

**Comment by veista** [comment]
You should get an entry in logbook after trying to configure the device. Also provide the pictures asked in read-me.

**Comment by whoami-pi** [comment]
Hi

thanks for your quick response. Please find attached pics from Nilan devices.

Thanks for checking!!

![image](https://user-images.githubusercontent.com/59413296/224529868-4c1cf1b6-581d-4cbd-825b-160e8042811b.jpeg)
![image](https://user-images.githubusercontent.com/59413296/224529870-a5a90781-7dae-4dc3-8e9e-71bd4aaa7a69.jpeg)
![image](https://user-images.githubusercontent.com/59413296/224529876-584f8438-9f1e-419a-baa3-42408082eacd.jpeg)
![image](https://user-images.githubusercontent.com/59413296/224529880-917b3065-5393-464c-8f01-c462173f2921.jpeg)

**Comment by whoami-pi** [comment]
This is actually where I stuck up. So, what I did:
1. Debug is active for HACS:
![image](https://user-images.githubusercontent.com/59413296/224533589-01793294-71b3-43ed-9e74-a3e97f72092e.png)
![image](https://user-images.githubusercontent.com/59413296/224533610-4eb50302-342b-4e3b-b455-85ed7c370db9.png)
2. Configuration.yaml: Have added these lines, saved the file, restarted HA
`# Logger`
`logger:`
`  default: info`
`  logs:`
`    custom_components.nilan: debug`
`    custom_components.hacs: debug`
3. (After new start STRG & F5 for cache) Add new integration, entered Nilan, selected SERIAL and following
![image](https://user-images.githubusercontent.com/59413296/224533491-e9977fc4-d441-4104-a68e-4d8a98002ef9.png)

4. Getting the issue related to unsupported device
5. Checking the Logbook, no entry for this integration
6. Even in home-assistant.log no entry related to this:
![image](https://user-images.githubusercontent.com/59413296/224533875-f73d0562-5ac2-40a8-b406-4c5dd91c2628.png)

I'm pretty sure that I'm doing something wrong...

**Comment by veista** [comment]
That should work. You don't need the HACS debugging.

**Comment by whoami-pi** [comment]
But still not able to see any entries in Log Book for Nilan or am I checking the wrong log book?
![image](https://user-images.githubusercontent.com/59413296/224535585-2d0236fe-6487-4c5e-aef3-13159b2c890a.png)

**Comment by veista** [comment]
> But still not able to see any entries in Log Book for Nilan or am I checking the wrong log book? ![image](https://user-images.githubusercontent.com/59413296/224535585-2d0236fe-6487-4c5e-aef3-13159b2c890a.png)

Yes. Go to settings->system->logs.

**Comment by whoami-pi** [comment]
Thanks, as I said, newbie at HA, here is an entry for Nilan, does it help you?

Logger: homeassistant.util.async_
Source: util/async_.py:159
First occurred: 10:35:30 (3 occurrences)
Last logged: 10:35:30

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for nilan doing blocking calls at custom_components/nilan/config_flow.py, line 59: result = client.read_holding_registers(

**Comment by veista** [comment]
DEBUG (MainThread) [custom_components.nilan.config_flow] Device Type XX not found in supported devices list

I meed this entry from logs.

**Comment by whoami-pi** [comment]
ok, now it should be the right one, hopefully, thanks for being patient with me :)

DEBUG (MainThread) [custom_components.nilan.config_flow] Device Type 12 not found in supported devices list

**Comment by veista** [comment]
Great. I will add your device ASAP.

**Comment by veista** [comment]
Support for your device is now in release 1.1.17
