### ISSUE TITLE
Comfort 300LR light -Various errors in HA

### ISSUE THREAD

**Issue by JakobPP** [veista/nilan#58]
Hello again

Everything running smoothly, with debug enabled I can see various errors repeating itself. Just thought Id throw them in here. Most of them you probably already know why theyre showing. Sorry for the lame formatting, just copy/pasta directly from the HA log viewer.

Could not read get_min_return_step
8:32:17 PM – (ERROR) Nilan (custom integration) - message first occurred at March 18, 2023 at 2:50:54 PM and shows up 27952 times
Could not read get_min_supply_step
8:32:16 PM – (ERROR) Nilan (custom integration) - message first occurred at March 18, 2023 at 2:50:54 PM and shows up 27953 times
Pymodbus: Nilan: Exception Response(131, 3, IllegalAddress)
8:32:16 PM – (ERROR) Modbus - message first occurred at March 18, 2023 at 2:50:54 PM and shows up 83879 times
Could not read get_hmi_language
8:32:14 PM – (ERROR) Nilan (custom integration) - message first occurred at March 18, 2023 at 2:50:54 PM and shows up 27953 times
Could not read get_high_humidity_step
8:32:12 PM – (ERROR) Nilan (custom integration) - message first occurred at 8:28:12 PM and shows up 2 times
Could not read get_t15_user_panel_temperature
8:32:09 PM – (ERROR) Nilan (custom integration) - message first occurred at March 18, 2023 at 2:49:21 PM and shows up 27964 times
Could not read get_max_return_step
8:32:07 PM – (ERROR) Nilan (custom integration) - message first occurred at March 18, 2023 at 2:50:54 PM and shows up 27952 times
Could not read get_supply_power_at_level_3
8:31:42 PM – (ERROR) Nilan (custom integration) - message first occurred at March 18, 2023 at 2:49:53 PM and shows up 3 times
Could not read get_max_supply_air_summer_setpoint
8:30:55 PM – (ERROR) Nilan (custom integration) - message first occurred at 8:29:17 PM and shows up 2 times
Could not read get_min_supply_air_winter_setpoint
8:30:54 PM – (ERROR) Nilan (custom integration) - message first occurred at 8:29:16 PM and shows up 2 times
Could not read get_smoke_alarm_state
8:30:52 PM – (ERROR) Nilan (custom integration) - message first occurred at 8:29:13 PM and shows up 2 times

**Comment by veista** [comment]
Great. Could you report your model as shoen by the integration. Also report modbus version.

Could you list the unavailable entities from the device view. Not all errors show in logs.

**Comment by JakobPP** [comment]
Sorry for the delay.

Modbus version 21.

When browsing via the app I see the following missing when viewing the device info.

User panel temperature (T15) - States unknown.

**Comment by veista** [comment]
That is very strange that you get invalid address errors in logs with modbus version 21. Could you tell me more about your setup? What kind of interface are you using?

**Comment by JakobPP** [comment]
Sorry for taking so long.

I have the Waveshare RS485 to ETH B gateway.

I can also see various "spikes and drops" on some of the logged values. I think control of the poll time would be a great addition, I think the 5 or 10 second poll is simply too much at times.

**Comment by veista** [comment]
Hi. I have decided to put the scan times to default values. Most sensors don't update so often anyway. It is not practical to implement a changeable scan time.
