### ISSUE TITLE
Configuration guidance for Sharewave Ethernet-to-RS485 converter

### ISSUE THREAD

**Issue by MKBU2** [veista/nilan#7]
Hi,

My setup:
- Nilan EC9 / CTS602
- Waveshare RS485 TO ETH (B) converter https://www.waveshare.com/wiki/RS485_TO_ETH_(B)
- Raspberry Pi 3 + Home Assistant
- Nilan integration installed from HACS

![image](https://user-images.githubusercontent.com/23105974/205868973-ace8a90e-5e9b-4254-bd42-66996b38daac.png)

![image](https://user-images.githubusercontent.com/23105974/205869108-9bfc30ea-0240-4990-baf8-e157e0844979.png)

I get "Invalid Response from Device" when trying to add the integration. Any ideas where the problem would be?

The modbus integration used to work in Openhab and previous USB-converter but I changed to ethernet-based for this specific integration in HA.

**Comment by veista** [comment]
Hi,

It propably is that your bridge is not ModBus TCP, but instead ModBus RTU over TCP. I havnt enabled official support for that yet, but you can try it by editing the device.py and replacing "tcp" with "rtuovertcp".

Nilan EC9 is not supperted yet, but I think you will help me with that.

**Comment by veista** [comment]
If that does not help, then you will have to try modifying the settings on your bridge. Please share the settings if you get it to work, it may help in future issues.

**Comment by veista** [comment]
Also I could add support for usb adapters, but I cannot debug this my self, so you would have to help me with that also and it might be difficult to do.

**Comment by veista** [comment]
> > If that does not help, then you will have to try modifying the settings on your bridge. Please share the settings if you get it to work, it may help in future issues.
> 
> This was on my mind because Sharewave seems to be quite popular and your integration very easy to install.
> 
> The manual doesn't clearly state that the converter could act in Modbus TCP state (if it isn't the NONE mode)
> 
> ![image](https://user-images.githubusercontent.com/23105974/205885237-b9fb6c05-f359-47c4-b949-f807fe0368b2.png)
> 
> Kiitos jo näistä vinkeistä.
> 

I would guess transparent is "rtuovertcp" and Modbus TCP is "tcp" so it should work. There might be some other setting that is wrong.

**Comment by veista** [comment]
Baudrate should be 19200 i think. And also destination and source ports should be both 502.

**Comment by veista** [comment]
Also make sure that your device id is 30. You can find this setting in the HMI menu.

**Comment by MKBU2** [comment]
Changed the ports to 502.

With all custom components/nilan files as defaul I get:
Waveshare / Multi-host settings / Protocol = **none** 
-> Invalid response From the device

Waveshare / Multi-host settings / Protocol = **Modbus TCP to RTU**
-> Unsupported Device

Something is changing..

**Comment by veista** [comment]
Hi, unsupported device is correct. Open a new issue with the information from the read-me instructions.
