### ISSUE TITLE
Unknown Device - Combi Polar 302 HMI

### ISSUE THREAD

**Issue by jamespreedy** [veista/nilan#74]
Hey there, thanks for your work on this integration.

I've tried to install, and I'm getting a device not supported error.

Device type plate below.

![Screenshot 2023-08-13 at 9 19 52 pm](https://github.com/veista/nilan/assets/559531/97cd3482-9744-4516-882b-2963a6ebe46f)

Photo showing "Show Data => Type" from CTS602 controller below.

![Screenshot 2023-08-13 at 9 21 45 pm](https://github.com/veista/nilan/assets/559531/681ee2f0-95a8-488c-8140-acac738641d2)

Believe from a previous post that this is what you need from the debug logs? If you need more, please let me know - will be very happy to help.

`2023-08-13 21:13:26.622 DEBUG (MainThread) [custom_components.nilan.config_flow] Device Type 33 not found in supported devices list`

Thanks in advance!

**Comment by veista** [comment]
Great, thanks! I will add this ASAP.

**Comment by jamespreedy** [comment]
@veista - thanks for the speedy response. Really appreciate it! Have a great week. 🍺
