### ISSUE TITLE
All sensors show same name

### ISSUE THREAD

**Issue by joriws** [veista/nilan#79]
Not nice - is this a feature of this integration?

![image](https://github.com/veista/nilan/assets/5603060/38db34f5-661e-462a-b2f3-6370b06c3943)

entity ids for adding sensor to cards are like:
![image](https://github.com/veista/nilan/assets/5603060/872a6ea2-598d-4b80-ba24-cd4fd7e6ce33)

**Comment by joriws** [comment]
I deleted integration and re-created, the same thing. HACS does not say update is available. I am running older core

![image](https://github.com/veista/nilan/assets/5603060/c0527f36-d374-4040-889a-3c5f1c3f4283)

![image](https://github.com/veista/nilan/assets/5603060/be17446f-3edb-4552-9ce0-7661a09f695a)

**Comment by veista** [comment]
My bad partially. I forgot to change minimum HA version .

**Comment by veista** [comment]
Will close this now. Sorry I can't support every HA version/device combination. You can try older releases and hope it has your device supported. I will be more mindfull of updating the HA requirement before release. This will not prevent misuse if installed manually though.
