### ISSUE TITLE
Failed to call service

### ISSUE THREAD

**Issue by AhmoBecks** [veista/nilan#81]
Issue is that services water_heater.turn_off and water_heater.turn_on cannot be called with Developer Tools. Also automations related to these services are not working. Still tough water heater can be turned on and off from dashboard. Workaround for this issue for me would be possibility to change water heater target temperature but that seems not to be an option in automations menu. Any idea what could cause this?

![image](https://github.com/veista/nilan/assets/142745442/5fe78b63-e479-4546-8cf1-2dfe192376b9)

**Comment by veista** [comment]
Hi, this is a feature of home assistant. Water heater does not have such service. The correct use is to use water heater set operation service. Read the documentation.
