### ISSUE TITLE
Doesn't work with 2023.9?

### ISSUE THREAD

**Issue by arjanmanders** [veista/nilan#84]
After updating to version 2023.9 of Hass, the integration couldn't find any entities? Worked before without issues, but after the update the entities were on state unavailable. After completely deleting the nilan integration and a reinstall, the integration has a setup failure, and no entities are added. The USR-TCP settings haven't been changed en is still connected to the network. (Same port) Rebooted my network (unify), my USR and home assistant, but nothing works..

**Comment by veista** [comment]
#80
