### ISSUE TITLE
Mapping Device Firmware Version to Modbus Version

### ISSUE THREAD

**Issue by veista** [veista/nilan#9]
Hi,

I am trying to support all devices in the Nilan CTS602 family, but the documentation is kind of lacking. If you are using this Integration and have a device outside of the following list, please comment here with your device firmware version and ModBus Version as stated by the integration.

Thank You!

Firmware: ModBus Version
2.00.q - 2.11.d: 1
2.11.e: 2
2.12.a - 2.15: 3
2.16.a - 2.20.a: 4
2.20.b - 2.21.a: 5
2.21.b - 2.30.a: 6
2.30.b - 2.30.e: 7
2.31.d: 8
2.35.a: 9
2.37.c: 11
2.38.r - 2.38.t: 19
1.1.25 - 1.6.21: 20
1.6.26: 21
1.6.43-1.6.56: 22

**Comment by Magifi** [comment]
Here’s mine:

![880126CA-62D2-4179-B442-0FC1BD76D365](https://user-images.githubusercontent.com/119972006/206848969-e9cffe52-1c6d-4adc-81c7-64177367932e.jpeg)
![10353BE0-0748-4DD7-8D43-C98F30FE3916](https://user-images.githubusercontent.com/119972006/206848975-b4cc727f-d080-4dfd-a20c-c84de62d8d1f.jpeg)
![F7F28F1F-A4F7-4C30-899D-7ABB935830D3](https://user-images.githubusercontent.com/119972006/206848976-efadb804-b534-43b0-b2f6-eadad87c513a.jpeg)

**Comment by veista** [comment]
Thanks, I would also need the Modbus Version. You can only find this info by reading it through ModBus.

**Comment by Magifi** [comment]
> Thanks, I would also need the Modbus Version. You can only find this info by reading it through ModBus.

2.21.a:5

Found it from openHAB items.

**Comment by llehti** [comment]
2.35.a: 9

**Comment by AlvinKleine** [comment]
Firmware: 2.38.t
Modbus version 19

**Comment by netforceatg** [comment]
VPL 25c / VPL 28c

Firmware: 2.37.c
Modbus version 11

**Comment by sainio** [comment]
VP 18cek
Firmware: 1.6.26
ModBus Version: 21

**Comment by Airler** [comment]
Firmware: 1.1.25
ModBus Version: 20

**Comment by nmkloster** [comment]
Firmware: 2.1.34 - ModBus version: 21

**Comment by ristoavila** [comment]
Firmware: 2.38r - Modbus Version: 19

**Comment by veista** [comment]
Thank you all for helping out with this issue! I will be closing this since all of the open questions I had have been anwsered.
